name: CI/CD - Build & Deploy to OCI

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: alelex10/backend-crm

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.set-tag.outputs.image_tag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag
        id: set-tag
        run: echo "::set-output name=image_tag::${GITHUB_SHA::8}"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image (latest and sha)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ steps.set-tag.outputs.image_tag }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Install ssh client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.OCI_SSH_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
      - name: Add host to known_hosts (optional -- prevents interactive prompt)
        run: |
          ssh-keyscan -H ${{ secrets.TARGET_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SSH - stop, pull and run
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.TARGET_HOST }}
          username: ${{ secrets.TARGET_USER }}
          key: ${{ secrets.OCI_SSH_KEY }}
          script: |

            CONTAINER_ID=$(docker ps -q --filter "publish=3001")
            if [ -n "$CONTAINER_ID" ]; then
            echo "🛑 Deteniendo contenedor que usa el puerto 3001 ($CONTAINER_ID)..."
            docker stop $CONTAINER_ID
            docker rm $CONTAINER_ID
            fi
            
            set -e
            IMAGE="alelex10/backend-crm:${{ needs.build-and-push.outputs.image_tag }}"
            CONTAINER_NAME="backend-crm"
            CONTAINER_PORT=3001

            docker stop $CONTAINER_NAME || true
            docker rm $CONTAINER_NAME || true

            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            docker pull $IMAGE

            docker run -d --name $CONTAINER_NAME -p $CONTAINER_PORT:3000 --restart unless-stopped $IMAGE
